### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by xuanli09** [cleanyong/oauth2play2scala#1]
First of all, great job for being the first to port amber/oltu to play scala. It's surprisingly hard to find an oauth server implementation in scala and even more so with play.

If I understand you correctly, you modified the HttpServerlet Request object to play.mvc.request through out amber, is there anything else you had to modify to port over?

**Comment by cleanyong** [comment]
Do you still have maven compile issue?

I changed something related to Option in Scala like:

====code====

Option<String> o = request.getQueryString(OAuth.OAUTH_STATE);            String state= o.isEmpty()?null:o.get();                        try{                if(state == null){                  play.api.mvc.AnyContent a = (play.api.mvc.AnyContent)(request.body());                                      if (a.asFormUrlEncoded().isDefined()){                      scala.collection.immutable.Map<String, scala.collection.Seq<String>> amap = a.asFormUrlEncoded().get();                     Option<scala.collection.Seq<String>> ao = amap.get(OAuth.OAUTH_STATE);                      String aos = ao.get().apply(0);                     state = aos;                    }                   }               }catch(Exception anyE){             //do nothing            }

====code====

**Comment by xuanli09** [comment]
Yea I fixed the maven compile issue, need to edit the pom.xml to tell it to use 1.6.
